### ISSUE TITLE
[SIM] kfx-broker-sim build 失败

### ISSUE THREAD

**Issue by GCWK** [kungfu-origin/kungfu#113]
### 系统
```
macOS Ventura 13.6.4
2.5 GHz 双核Intel Core i7
内存 16G 

python 3.9.18
cmake 3.28.3
yarn 1.22.4
nodejs 18.18.0
```
### 问题
```
@kungfu-trader/kfx-broker-sim
$ kfs extension build
 | -- writing workflows ...
 | -- /Users/wkgc/workspace/kungfu/.github/CODEOWNERS exists, skip copy
 | -- /Users/wkgc/workspace/kungfu/.github/workflows/bump-major-version.yml exists, skip copy
 | -- /Users/wkgc/workspace/kungfu/.github/workflows/bump-minor-version.yml exists, skip copy
 | -- /Users/wkgc/workspace/kungfu/.github/workflows/release-new-version.yml exists, skip copy
 | -- /Users/wkgc/workspace/kungfu/.github/workflows/release-verify.yml exists, skip copy
 | -- written to /Users/wkgc/workspace/kungfu/.github
$ /Users/wkgc/workspace/kungfu/node_modules/.bin/kfc engage pdm makeup
 | Changes are written to pyproject.toml.
$ /Users/wkgc/workspace/kungfu/node_modules/.bin/kfc engage pdm install
Usage: kfc [OPTIONS] COMMAND [ARGS]...
 |
 | Error: No such option: -s
 | See /var/folders/gl/r0tvshcx6pz6xlrswdp3wvpc0000gn/T/pdm-install-5d_9_9ex.log
 | for detailed debug log.
 | [CalledProcessError]: Command
 | '['/Users/wkgc/workspace/kungfu/framework/core/dist/kfc/kfc', '-sS', '-c',
 | 'import platform; print(platform.mac_ver()[0])']' returned non-zero exit status
 | 2.
 | Add '-v' to see the detailed traceback
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | Failed to execute $ yarn kfc engage pdm install
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn build` failed with exit code 1
Stopping 10 active children
Aborted execution due to previous error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kungfu-origin** [comment]
请问执行这段命令输出什么结果？
yarn kfc engage pdm --version

**Comment by GCWK** [comment]
yarn run v1.22.4
$ /Users/wkgc/workspace/kungfu/node_modules/.bin/kfc engage pdm --version
PDM, version 2.5.6
✨  Done in 9.20s.

**Comment by ayizhi** [comment]
> yarn run v1.22.4 $ /Users/wkgc/workspace/kungfu/node_modules/.bin/kfc engage pdm --version PDM, version 2.5.6 ✨ Done in 9.20s.

1. 需要确保 x86的python(/usr/local/homebrew内)在环境变量比较靠前的位置，确保功夫编译的时候能够走x86的python，建议取消掉 /opt/homebrew/bin 下的python 链接
![Screenshot 2024-03-05 at 16 17 28](https://github.com/kungfu-origin/kungfu/assets/14844688/36e483ea-6ddb-49f5-bbe8-cecd353b8717)

**Comment by GCWK** [comment]
@ayizhi 
并不是m1芯片，仍然是intel芯片，且编译时所使用的python环境，是conda create的独立的python 3.9环境，不会调用系统全局python

**Comment by ayizhi** [comment]
> @ayizhi 并不是m1芯片，仍然是intel芯片，且编译时所使用的python环境，是conda create的独立的python 3.9环境，不会调用系统全局python

conda 的环境貌似有问题，建议用brew安装的python，并且确保编译时识别到的python为brew 安装，确认方式在上条回复的截图

**Comment by kungfu-origin** [comment]
请问执行如下是什么结果呢：
KFC_AS_VARIANT=python /Users/wkgc/workspace/kungfu/framework/core/dist/kfc/kfc --version

**Comment by GCWK** [comment]
<img width="710" alt="image" src="https://github.com/kungfu-origin/kungfu/assets/20805886/3450229b-2198-48d2-be07-7c4cda9d75ce">

**Comment by GCWK** [comment]
[pdm-install-5d_9_9ex.log](https://github.com/kungfu-origin/kungfu/files/14492656/pdm-install-5d_9_9ex.log)
我觉得不是python的问题，当然可能我是错的，只是从报错结果来看，是因为kfc 命令缺少一些option，至于为何会执行到需要调用-sS -c之类的，是否跟pdm打包有关

**Comment by kungfu-origin** [comment]
> <img alt="image" width="710" src="https://private-user-images.githubusercontent.com/20805886/310042661-3450229b-2198-48d2-be07-7c4cda9d75ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjgzOTAsIm5iZiI6MTcwOTYyODA5MCwicGF0aCI6Ii8yMDgwNTg4Ni8zMTAwNDI2NjEtMzQ1MDIyOWItMjE5OC00OGQyLWJlMDctN2M0Y2RhOWQ3NWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA4NDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxN2M2Y2E1NmQ4ODFkNzAxODVlMTM1YThkN2RjM2M2NzI4ZTJjZTdjYzk1YzVhY2UxOWJjYjAxYjVkOTMwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WucE5Esh_HmfSarRCY83xYNuiFj9Qdjnt0A5TvyerFk">

这说明是kfc是能正确识别的，你直接在 extensions/sim 下执行 yarn build 试试？

**Comment by GCWK** [comment]
错误是一样的
<img width="711" alt="image" src="https://github.com/kungfu-origin/kungfu/assets/20805886/69e8ed5c-aa40-4331-b943-699ce219cd41">

**Comment by kungfu-origin** [comment]
在 extensions/sim 下直接执行：
/Users/wkgc/workspace/kungfu/framework/core/dist/kfc/kfc engage pdm install

**Comment by kungfu-origin** [comment]
确实也有可能是conda环境的问题，如果还是不行的话建议换一个本机python版本试试；功夫是用pipenv来创建隔离环境的，不会对你的本机python造成任何影响。

**Comment by GCWK** [comment]
https://blog.csdn.net/m0_48732747/article/details/135083125
其实是 macOS 在 x86 架构下的一个 bug，导致尽管 macOS 已经升级过了，仍然按照 10.16 版本进行处理
<img width="573" alt="image" src="https://github.com/kungfu-origin/kungfu/assets/20805886/21380000-144f-4f8a-9cba-d385d143f7e5">
