### ISSUE TITLE
策略隔天后，不能获取行情

### ISSUE THREAD

**Issue by daiab** [kungfu-origin/kungfu#13]
一个策略启动后，过一晚上，md_engine就不会调用on_bar或则on_ticker函数了。不知道是不是yjj中的engine_start/end_time的问题

**Comment by jqlruc** [comment]
我有同样的问题  上午、下午、夜盘、次日 策略在任意时间段开启都能正常交易 但是不能延续到下一个时间段

**Comment by spyhole** [comment]
咬他

**Comment by omytea** [comment]
I have not gone through yjj code. What I tested is, after onDisconnected of ctp is called, an ENGINE_OPEN message have to be sent to md engine. Then ctp api would be restarted and instruments would be subscribed again

**Comment by GGZNZ** [comment]
一样的我问题，我从27日开始运行basicusage策略，输出日期时间开盘，收盘价等，28日，就没有接收到其他信息。

**Comment by SheldonNico** [comment]
一样的问题，临时解决办法是需要在kungfuctl里 restart md_ctp，然后还要重启所有的策略（即使新策略能接收不到行情，昨天运行的策略还是接收不到行情，即使都能在yjj里看到）。
不知道有人解决了吗？
