### ISSUE TITLE
error centos7+python2.7.5

### ISSUE THREAD

**Issue by mercury20160104** [kungfu-origin/kungfu#40]
……
-- Performing Test HAS_FLTO - Success
-- LTO enabled
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY (ADVANCED)
    linked by target "strategy_util" in directory /opt/kungfu/v2.0/kungfu/cpp/wingchun/strategy

-- Configuring incomplete, errors occurred!
See also "/opt/kungfu/v2.0/kungfu/build/CMakeFiles/CMakeOutput.log".
See also "/opt/kungfu/v2.0/kungfu/build/CMakeFiles/CMakeError.log".
ERR! OMG Process terminated: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mercury20160104** [comment]
目前已经解决，同时都可以支持Python2.7.5和Python3.6.5。

**Comment by joytrust0609** [comment]
请问如何解决的？

**Comment by joytrust0609** [comment]
请问是如何解决的？ @mercury20160104

**Comment by mercury20160104** [comment]
建立一个软连接libpython. so

在 2019-05-28 17:08:50，Justin <notifications@github.com> 写道：


请问如何解决的？
