### ISSUE TITLE
English language for Windows build please

### ISSUE THREAD

**Issue by lucatortiglione** [kungfu-origin/kungfu#74]
Hi, how can i get english language for Windows Build ?

Thank you.

**Comment by ArtificialZeng** [comment]
> Hi, how can i get english language for Windows Build ?
> 
> Thank you.

you can use Google translate

**Comment by lostboy123** [comment]
&nbsp;I am sorry ！ I never build in English！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kungfu-origin/kungfu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 下午3:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [kungfu-origin/kungfu] English language for Windows build please (#74)





  
Hi, how can i get english language for Windows Build ?
 
Thank you.
  
you can use Google translate
